title = "Sunset Dunes Local Businesses"

[[businesses]]
id = "cafe-01"
name = "Espresso Station"
type = ["cafe"]
lat = 37.7749
long = -122.4194
address = "123 Main St"
phone = "555-0199"
description = "Best dark roast in town."
    [businesses.hours]
    monday = "07:00-16:00"
    tuesday = "07:00-16:00"
    wednesday = "07:00-16:00"
    thursday = "07:00-16:00"
    friday = "07:00-16:00"
    saturday = "08:00-14:00"
    sunday = "Closed"

    [businesses.holiday_hours]
    "2025-12-25" = "Closed"
    "2026-01-01" = "10:00-14:00"

[[businesses]]
id = "blackbird books"
name = "black Bird Books & Caf√©"
type = ["bookstore", "cafe"]
address = "4033 Irving St, San Francisco, CA 94122"
phone = "415 555-0200"
description = "Curated Book store with great kids section and wonderful coffee and pastries"
    [businesses.hours]
    default = "11:00-22:00" # Fallback if a specific day isn't listed
    sunday = "12:00-20:00"

    [businesses.holiday_hours]
    "2025-12-25" = "Closed"
    "2026-01-01" = "10:00-14:00"

# Generic areas of interest for QR code placement
[[locations]]
id = "lawton"
name = "Lawton & Sunset Dunes"
lat = 37.75651
long = -122.50924
zoom = 18 # Optional: override default zoom
